name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 监听master分支的push事件

jobs:
  deploy:
    runs-on: ubuntu-latest  # 运行在最新的Ubuntu虚拟机上
    steps:
    - uses: actions/checkout@v4  # 检出代码

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub提供的token
      run: |
        git config --global user.email "git@cmsz.us.kg"  # 设置git用户email
        git config --global user.name "CMSZ"  # 设置git用户名
        git checkout master
        git merge gh-pages
        
